import = [
  "~/.config/alacritty/colorschemes/catppuccin-mocha.toml"
]

[font]
normal = { family = "FiraMono Nerd Font Propo" }
size   = 14

[selection]
save_to_clipboard = true

[bell]
animation = 'EaseOut'
duration  = 50

[window]
decorations     = "None"
padding         = { x = 5, y = 2 }
dynamic_padding = true
startup_mode    = "Maximized"
