* Alacritty

  My reason to use Alacritty is to have a Terminal Emulator capable of True Color, so I can use Vim with all the glorious colors of [[https://github.com/catppuccin][Catppuccin Theme]].

  Use [[https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraMono.zip][FiraMono Nerd Font]] to have nice Terminal Icons.

  I like the behavior of automatically copying the selection to clipboard.

  I prefer to have a visual alert instead sound one. So, I don't need phones all the time. And I don't wake up the kids ;)

  Given Alacritty didn't implement tabs, neither has any plan to do it, I don't need to worry about space for the list of tabs.
  It should start maximized to use the whole screen space. I only need a little space to avoid the feeling the app size is beyond the visible screen.

  I tried to replicate the default MacOS Terminal "clear screen and empty terminal history". But, the closest I got was ~Cmd + k~ twice. One for ~clear screen~ and one for ~clear history~.

  I'll [[https://ansidev.xyz/posts/2023-04-16-how-to-solve-alt-key-binding-issue-on-macos][use Option as ALT to allow Vim and Tmux keybidings using Alt]]
